version: '3.3'

services:
  named:
    image: ubuntu/bind9
    volumes:
      - ./data/zones:/var/named
      - ./config/named:/etc/bind
    networks:
      docker:
        ipv4_address: 172.21.21.3

  flask_app_test:
    build: ./images/flask
    command: /bin/sh -c "pylint /opt/app --recursive=true ; pytest -vv -n 8 /opt/app"
    volumes:
      - ./config/named/ddnskey.conf:/etc/ddnskey.conf
    networks:
      docker:
        ipv4_address: 172.21.21.4
    depends_on:
      - named

networks:
  docker:
    ipam:
      config:
        - subnet: 172.21.21.0/24


