name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: LINLEE

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: install essential utils
      run: sudo apt update && sudo apt install -y bind9 bind9utils

    - name: Running test
      run: make init && make test

    - name: Calling jenkins to deploy
      run: curl -X POST ${{ LINLEE.JENKINS_URL }}
